### ISSUE TITLE
Crashes with 4 vcf files 

### ISSUE THREAD

**Issue by dollinad** [dancooke/starfish#3]
Hi, 

I tried starfish to intersect 3 vcf files and works absolutely fine but crashes with 4 with the following error.

`Traceback (most recent call last):
  File "starfish.py", line 334, in <module>
   main(parsed)
  File "starfish.py", line 206, in main
    naive_intersect(vcfs[i], isecs, tail_mask, out_vcf)
  File "starfish.py", line 138, in naive_intersect
    remove_vcf(common_positive_temp_vcf)
  File "starfish.py", line 45, in remove_vcf
    os.remove(vcf_fname)
  FileNotFoundError: [Errno 2] No such file or directory: '/Output/AD.vcf.gz.temp'
`

I am running this command in a conda environment witth python3 (linux centos 7)

`python starfish.py -
-rtg rtg -
-sdf hg38_no_alt.sdf
-V path_to_vcf1.vcf.gz path_to_vcf2.vcf.gz path_to_vcf3.vcf.gz path_to_vcf4.vcf.gz
 -O Output
`
 
Thanks, 
Dollina

**Comment by dancooke** [comment]
Could you try downloading the version I just pushed and re-run with the new `--verbose` option, then post whatever output is produced?

**Comment by dollinad** [comment]
I got this error 
`Traceback (most recent call last):
  File "starfish.py", line 353, in <module>
    main(parsed)
  File "starfish.py", line 217, in main
    naive_intersect(vcfs[i], isecs, tail_mask, out_vcf, debug=args.verbose)
TypeError: naive_intersect() got an unexpected keyword argument 'debug'
`

**Comment by dancooke** [comment]
Ah. Please try again with latest commit.

**Comment by dollinad** [comment]
Hi Daniel, 

That works! Thank you. 

However, we had an issue with bcftools concat since it need the vcfs provided to have only one sample with the same name across. 

I chanced the concat command to merge and now get a few vcfs named 2-, 2, 2+, 3-, 3, 3+, .... 
I was wondering if this change is okay and what is the purpose of the vcfs above?

Thanks, 
Dollina

**Comment by dancooke** [comment]
The purpose of these VCFs is to show which records are partially supported by the number of input VCFs indicated on the filename. For example, `3-.vcf.gz` contains records supported by 3 or less of the input VCFs while `2.vcf.gz` contains records supported by exactly 2 input VCFs.

You're right that the `concat` command doesn't work with unmatched sample, but I don't believe that `merge` is really suitable either. For example, if you have three input VCFs `A.vcf.gz`, `B.vcf.gz`, and `C.vcf.gz` then you'll have intersect files `AB.vcf.gz`, `AC.vcf.gz`, `BC.vcf.gz`, and `ABC.vcf.gz`. Now the partial support VCF `2.vcf.gz` should contain the union of all records in `AB.vcf.gz`, `AC.vcf.gz` and `BC.vcf.gz`, but the representation and sample columns for each of these VCFs is derived from the first VCF present (i.e. `A`, `A`, and `B`, respectively). So you'll end up trying to merge overlapping sample sets, which isn't allowed by `bcftools merge`. You can use `--force-sample`, but then you get weird genotypes where you don't know which genotype came from which sample. It's probably better just to drop sample information in these cases.

**Comment by dancooke** [comment]
I just committed a change that used `bcftools merge` in cases with unmatched VCF inputs.
