### ISSUE TITLE
missing  tmp file

### ISSUE THREAD

**Issue by ghost** [dancooke/starfish#4]
Hello, here what happened, with 11 vcf

```
./starfish/starfish.py --sdf shasta_SDF --rtg rtg-tools/build/executable/rtg --threds 4 -V *.filtered.g.vcf.gz -O isec
Traceback (most recent call last):
  File "./starfish/starfish.py", line 375, in <module>
    main(parsed)
  File "./starfish/starfish.py", line 239, in main
    naive_intersect(vcfs[i], isecs, tail_mask, out_vcf, debug=args.verbose)
  File "./starfish/starfish.py", line 144, in naive_intersect
    remove_vcf(common_positive_temp_vcf)
  File "./starfish/starfish.py", line 49, in remove_vcf
    os.remove(vcf_fname)
FileNotFoundError: [Errno 2] No such file or directory: 'isec/AB.vcf.gz.temp'

```
indeed the temp file is not there.

**Comment by ghost** [comment]
I reran it with "verbose mode" and now the error has changed

`Failed to open isec/ABCFG.vcf.gz: could not load index`
However, the index is there 

```
ls isec/ABCFG.vcf.gz.*
isec/ABCFG.vcf.gz.tbi
```
I attach the full log
[starfish.log](https://github.com/dancooke/starfish/files/4239388/starfish.log)

**Comment by dancooke** [comment]
Possibly you're hitting your OS open file limit. Try again after setting `ulimit -n 10000` or as high as possible.

**Comment by ghost** [comment]
> Possibly you're hitting your OS open file limit. Try again after setting `ulimit -n 10000` or as high as possible.

Ah that's very likely, I keep you updated if this solves it.

**Comment by dancooke** [comment]
Did this solve the issue; can I close?

**Comment by ghost** [comment]
Yes it did! 
thank you
